### ISSUE TITLE
[Bug] <package is not working natively>

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

The project is not working natively i.e it only works when you install it globally  "npm install -g db-drawer". It is not working with "npm install db-drawer"
### 

### Expected Behaviour

The projects should work with both "npm install db-drawer" and "npm install -g db-drawer"

### Environment

```markdown
- OS:Linux mint 21
- Node: 20.12.2
- npm: 10.7.0
```

**Comment by Shobhit-Nagpal** [comment]
hey, would love to look into this issue under gssoc' 24.

looked at the npm website for db-drawer and at first glance, the reason i think that the commands work only when globally installed is because when we install an npm package locally, we have to invoke it with npm run <package_name> <flags>.

in the example given, it directly executes db-draw without the npm run.

**Comment by Bhanu-code** [comment]
@Shobhit-Nagpal ok, assigning to you. Fix it and raise PR.

**Comment by Shobhit-Nagpal** [comment]
hey @Bhanu-code, turns out the package is actually working locally as well. here's what is happening:

- when we run npm install db-drawer, it pulls the package from the registry and places it inside node_modules.
- node_modules has a .bin/ directory which contains all the binary executables for the packages.
- the db-drawer has index.js as it's binary executable file which is great.
- the catch is, if we want to run the db-draw command locally, we have to use `npx db-draw m` and not npm or db-draw directly

the npx package runs the binary executable of the package in the node_modules/.bin/ directory.

when we do npm run <package_name>, it will look for commands present under scripts in package.json of the project and not the executables.

one thing to note is, when people install this package, it's better to install it as a dev dependency (something to mention in the docs)

attaching screenshot of working below:

![image](https://github.com/Bhanu-code/db-drawer/assets/74096450/2b7a291f-d8b1-4528-ba59-63c5cf2d45fb)

all there is to do is update the README documentation for using the package and publishing it to npm. you want me to update the documentation and send over a pr?

**Comment by Bhanu-code** [comment]
@Shobhit-Nagpal nice! Then mapping the existing command with npx db-draw m will solve the problem

**Comment by Shobhit-Nagpal** [comment]
@Bhanu-code we don't need to map anything either. the package works as it is. i did not make any changes to the package. just need to update docs

**Comment by Bhanu-code** [comment]
@Shobhit-Nagpal ok go ahead!

**Comment by Shobhit-Nagpal** [comment]
@Bhanu-code cool, working on it. do you mind adding the gssoc labels on this issue btw?

**Comment by Bhanu-code** [comment]
@Shobhit-Nagpal added label, go ahead!

**Comment by Shobhit-Nagpal** [comment]
@Bhanu-code raised the pr. if all changes look good and the pr is merged, you would have to publish it on npm to update the docs on there.

if there's any changes before that, do let me know

**Comment by Shobhit-Nagpal** [comment]
hey @Bhanu-code, sorry to disturb you about this but could you add the label which mentions the level as well? 

the mentors mentioned that it's essential to adding up points.

thanks in advance :)
